### ISSUE TITLE
shapefile download

### ISSUE THREAD

**Issue by justinelliotmeyers** [mapaction/RAMP-South-Sudan-Settlements#5]
hello,
is there shapefile data within this repo?

thank you for your time and help,
justin

**Comment by ncmcw** [comment]
Hi Justin,
Others who were involved in the project at the time might have more to add. But for now, my understanding is:
- The results of this project were incorporated into OCHA's common operational dataset (COD) at the time, and published on HDX.
- That dataset has since been superseded by others published by OCHA South Sudan.
- Be aware that the HDX tagging for these datasets has some inconsistencies, but in short:
- The most recent seems to be https://data.humdata.org/dataset/south-sudan-settlements (it says geojson, but in fact it's shp)
- Although it's still tagged as a COD, this seems to be an earlier version https://data.humdata.org/dataset/south-sudan-settlement-data 
- You might also like to look at the datasets published GRID3 and HOT.

If it's for a humanitarian application, let us know if we can help further.

Cheers, Nick

**Comment by justinelliotmeyers** [comment]
@ncmcw Thank you very much. I believe this is what I needed to know. Anything in Africa is hard. Especially when there is war, famine, disaster... Appreciate you and your team getting data out there and helping the people there.

Have a great week.
Justin
